## YAML Template.
---
indexSuccess:
  metas:
    title: Lịch sử giao dịch SMS
  stylesheets:
    - bootstrapDaterangepickerMaster/daterangepicker-bs2.css

  javascripts:
    - bootstrapDaterangepickerMaster/moment.min.js
    - bootstrapDaterangepickerMaster/daterangepicker.js