<?php

/**
 * BaseTaxDailyStatictis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $taxId
 * @property datetime $day
 * @property integer $gameId
 * @property integer $taxValue
 * @property integer $isCash
 * @property timestamp $insertedTime
 * 
 * @method integer           getTaxId()        Returns the current record's "taxId" value
 * @method datetime          getDay()          Returns the current record's "day" value
 * @method integer           getGameId()       Returns the current record's "gameId" value
 * @method integer           getTaxValue()     Returns the current record's "taxValue" value
 * @method integer           getIsCash()       Returns the current record's "isCash" value
 * @method timestamp         getInsertedTime() Returns the current record's "insertedTime" value
 * @method TaxDailyStatictis setTaxId()        Sets the current record's "taxId" value
 * @method TaxDailyStatictis setDay()          Sets the current record's "day" value
 * @method TaxDailyStatictis setGameId()       Sets the current record's "gameId" value
 * @method TaxDailyStatictis setTaxValue()     Sets the current record's "taxValue" value
 * @method TaxDailyStatictis setIsCash()       Sets the current record's "isCash" value
 * @method TaxDailyStatictis setInsertedTime() Sets the current record's "insertedTime" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxDailyStatictis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tax_daily_statictis');
        $this->hasColumn('taxId', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('day', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             'comment' => '',
             ));
        $this->hasColumn('gameId', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'id game',
             'length' => 5,
             ));
        $this->hasColumn('taxValue', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => '0: deactive, 1:active',
             'length' => 5,
             ));
        $this->hasColumn('isCash', 'integer', 1, array(
             'type' => 'integer',
             'comment' => '1: cash, 0: gold',
             'length' => 1,
             ));
        $this->hasColumn('insertedTime', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}