<?php

/**
 * BaseWebContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $image
 * @property string $content
 * @property string $title
 * @property boolean $status
 * @property integer $type
 * @property boolean $is_hot
 * @property string $keywords
 * @property string $description
 * 
 * @method string     getImage()       Returns the current record's "image" value
 * @method string     getContent()     Returns the current record's "content" value
 * @method string     getTitle()       Returns the current record's "title" value
 * @method boolean    getStatus()      Returns the current record's "status" value
 * @method integer    getType()        Returns the current record's "type" value
 * @method boolean    getIsHot()       Returns the current record's "is_hot" value
 * @method string     getKeywords()    Returns the current record's "keywords" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method WebContent setImage()       Sets the current record's "image" value
 * @method WebContent setContent()     Sets the current record's "content" value
 * @method WebContent setTitle()       Sets the current record's "title" value
 * @method WebContent setStatus()      Sets the current record's "status" value
 * @method WebContent setType()        Sets the current record's "type" value
 * @method WebContent setIsHot()       Sets the current record's "is_hot" value
 * @method WebContent setKeywords()    Sets the current record's "keywords" value
 * @method WebContent setDescription() Sets the current record's "description" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('web_content');
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Link hình ảnh',
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 8000, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Nội dung',
             'length' => 8000,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Tieu de',
             'length' => 100,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'comment' => '0 tạo mới, 1 active',
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => '0: tin tức, 1 sự kiện, 2 giới thiệu, 3 hỗ trợ, 4 luật game',
             'length' => 1,
             ));
        $this->hasColumn('is_hot', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'comment' => '1: top hot',
             ));
        $this->hasColumn('keywords', 'string', 256, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'keywords',
             'length' => 256,
             ));
        $this->hasColumn('description', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'description',
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}