<?php

/**
 * BaseUserOTP
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $user_id
 * @property string $verify_code
 * @property timestamp $expried_time
 * @property string $mo_id
 * @property string $msisdn
 * @property int $type
 * @property integer $status
 * 
 * @method bigint    getUserId()       Returns the current record's "user_id" value
 * @method string    getVerifyCode()   Returns the current record's "verify_code" value
 * @method timestamp getExpriedTime()  Returns the current record's "expried_time" value
 * @method string    getMoId()         Returns the current record's "mo_id" value
 * @method string    getMsisdn()       Returns the current record's "msisdn" value
 * @method int       getType()         Returns the current record's "type" value
 * @method integer   getStatus()       Returns the current record's "status" value
 * @method UserOTP   setUserId()       Sets the current record's "user_id" value
 * @method UserOTP   setVerifyCode()   Sets the current record's "verify_code" value
 * @method UserOTP   setExpriedTime()  Sets the current record's "expried_time" value
 * @method UserOTP   setMoId()         Sets the current record's "mo_id" value
 * @method UserOTP   setMsisdn()       Sets the current record's "msisdn" value
 * @method UserOTP   setType()         Sets the current record's "type" value
 * @method UserOTP   setStatus()       Sets the current record's "status" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserOTP extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_otp');
        $this->hasColumn('user_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('verify_code', 'string', 32, array(
             'type' => 'string',
             'comment' => 'Mệnh giá thẻ cào hoặc giá niêm yết của hiện vật',
             'length' => 32,
             ));
        $this->hasColumn('expried_time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => '',
             ));
        $this->hasColumn('mo_id', 'string', 256, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'map voi bang mo_log',
             'length' => 256,
             ));
        $this->hasColumn('msisdn', 'string', 15, array(
             'type' => 'string',
             'comment' => '',
             'length' => 15,
             ));
        $this->hasColumn('type', 'int', 2, array(
             'type' => 'int',
             'comment' => 'kiểu otp: 0 xác thực tai khoan, 1 reset mật khẩu',
             'length' => 2,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => '0: chua su dung, 1:da su dung',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}