<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MoHistory', 'doctrine');

/**
 * BaseMoHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $id
 * @property bigint $mo_id
 * @property bigint $phone_number
 * @property bigint $user_id
 * @property bigint $amount
 * @property string $transdate
 * @property string $shortcode
 * @property string $keyword
 * @property string $content
 * @property string $telco
 * @property int $status
 * 
 * @method bigint    getId()           Returns the current record's "id" value
 * @method bigint    getMoId()         Returns the current record's "mo_id" value
 * @method bigint    getPhoneNumber()  Returns the current record's "phone_number" value
 * @method bigint    getUserId()       Returns the current record's "user_id" value
 * @method bigint    getAmount()       Returns the current record's "amount" value
 * @method string    getTransdate()    Returns the current record's "transdate" value
 * @method string    getShortcode()    Returns the current record's "shortcode" value
 * @method string    getKeyword()      Returns the current record's "keyword" value
 * @method string    getContent()      Returns the current record's "content" value
 * @method string    getTelco()        Returns the current record's "telco" value
 * @method int       getStatus()       Returns the current record's "status" value
 * @method MoHistory setId()           Sets the current record's "id" value
 * @method MoHistory setMoId()         Sets the current record's "mo_id" value
 * @method MoHistory setPhoneNumber()  Sets the current record's "phone_number" value
 * @method MoHistory setUserId()       Sets the current record's "user_id" value
 * @method MoHistory setAmount()       Sets the current record's "amount" value
 * @method MoHistory setTransdate()    Sets the current record's "transdate" value
 * @method MoHistory setShortcode()    Sets the current record's "shortcode" value
 * @method MoHistory setKeyword()      Sets the current record's "keyword" value
 * @method MoHistory setContent()      Sets the current record's "content" value
 * @method MoHistory setTelco()        Sets the current record's "telco" value
 * @method MoHistory setStatus()       Sets the current record's "status" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMoHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mo_history');
        $this->hasColumn('id', 'bigint', 20, array(
             'type' => 'bigint',
             'primary' => true,
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('mo_id', 'bigint', 11, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 11,
             ));
        $this->hasColumn('phone_number', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('user_id', 'bigint', 15, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 15,
             ));
        $this->hasColumn('amount', 'bigint', 15, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 15,
             ));
        $this->hasColumn('transdate', 'string', 256, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => '',
             'length' => 256,
             ));
        $this->hasColumn('shortcode', 'string', 256, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => '',
             'length' => 256,
             ));
        $this->hasColumn('keyword', 'string', 32, array(
             'type' => 'string',
             'comment' => 'keyword tin nhan',
             'length' => 32,
             ));
        $this->hasColumn('content', 'string', 256, array(
             'type' => 'string',
             'comment' => '',
             'length' => 256,
             ));
        $this->hasColumn('telco', 'string', 10, array(
             'type' => 'string',
             'comment' => 'mã nhà mạng',
             'length' => 10,
             ));
        $this->hasColumn('status', 'int', 2, array(
             'type' => 'int',
             'comment' => '',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}