<?php

/**
 * BaseLoggedInLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $logId
 * @property bigint $userId
 * @property string $userName
 * @property timestamp $loggedInTime
 * @property string $deviceId
 * @property string $deviceInfo
 * @property string $remoteIp
 * @property int $clientType
 * @property string $packageName
 * @property int $versionCode
 * @property string $versionBuild
 * @property int $ipLocked
 * @property int $reloggedIn
 * 
 * @method integer     getLogId()        Returns the current record's "logId" value
 * @method bigint      getUserId()       Returns the current record's "userId" value
 * @method string      getUserName()     Returns the current record's "userName" value
 * @method timestamp   getLoggedInTime() Returns the current record's "loggedInTime" value
 * @method string      getDeviceId()     Returns the current record's "deviceId" value
 * @method string      getDeviceInfo()   Returns the current record's "deviceInfo" value
 * @method string      getRemoteIp()     Returns the current record's "remoteIp" value
 * @method int         getClientType()   Returns the current record's "clientType" value
 * @method string      getPackageName()  Returns the current record's "packageName" value
 * @method int         getVersionCode()  Returns the current record's "versionCode" value
 * @method string      getVersionBuild() Returns the current record's "versionBuild" value
 * @method int         getIpLocked()     Returns the current record's "ipLocked" value
 * @method int         getReloggedIn()   Returns the current record's "reloggedIn" value
 * @method LoggedInLog setLogId()        Sets the current record's "logId" value
 * @method LoggedInLog setUserId()       Sets the current record's "userId" value
 * @method LoggedInLog setUserName()     Sets the current record's "userName" value
 * @method LoggedInLog setLoggedInTime() Sets the current record's "loggedInTime" value
 * @method LoggedInLog setDeviceId()     Sets the current record's "deviceId" value
 * @method LoggedInLog setDeviceInfo()   Sets the current record's "deviceInfo" value
 * @method LoggedInLog setRemoteIp()     Sets the current record's "remoteIp" value
 * @method LoggedInLog setClientType()   Sets the current record's "clientType" value
 * @method LoggedInLog setPackageName()  Sets the current record's "packageName" value
 * @method LoggedInLog setVersionCode()  Sets the current record's "versionCode" value
 * @method LoggedInLog setVersionBuild() Sets the current record's "versionBuild" value
 * @method LoggedInLog setIpLocked()     Sets the current record's "ipLocked" value
 * @method LoggedInLog setReloggedIn()   Sets the current record's "reloggedIn" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLoggedInLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logged_in_log');
        $this->hasColumn('logId', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('userId', 'bigint', 15, array(
             'type' => 'bigint',
             'comment' => '',
             'length' => 15,
             ));
        $this->hasColumn('userName', 'string', 20, array(
             'type' => 'string',
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('loggedInTime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('deviceId', 'string', 20, array(
             'type' => 'string',
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('deviceInfo', 'string', 20, array(
             'type' => 'string',
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('remoteIp', 'string', 20, array(
             'type' => 'string',
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('clientType', 'int', 2, array(
             'type' => 'int',
             'comment' => '',
             'length' => 2,
             ));
        $this->hasColumn('packageName', 'string', 20, array(
             'type' => 'string',
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('versionCode', 'int', 5, array(
             'type' => 'int',
             'comment' => '',
             'length' => 5,
             ));
        $this->hasColumn('versionBuild', 'string', 20, array(
             'type' => 'string',
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('ipLocked', 'int', 2, array(
             'type' => 'int',
             'comment' => '',
             'length' => 2,
             ));
        $this->hasColumn('reloggedIn', 'int', 2, array(
             'type' => 'int',
             'comment' => '',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}