<?php

/**
 * BaseEmergencyNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $notificationId
 * @property string $content
 * @property timestamp $createdTime
 * @property timestamp $expriedTime
 * @property int $active
 * 
 * @method integer               getNotificationId() Returns the current record's "notificationId" value
 * @method string                getContent()        Returns the current record's "content" value
 * @method timestamp             getCreatedTime()    Returns the current record's "createdTime" value
 * @method timestamp             getExpriedTime()    Returns the current record's "expriedTime" value
 * @method int                   getActive()         Returns the current record's "active" value
 * @method EmergencyNotification setNotificationId() Sets the current record's "notificationId" value
 * @method EmergencyNotification setContent()        Sets the current record's "content" value
 * @method EmergencyNotification setCreatedTime()    Sets the current record's "createdTime" value
 * @method EmergencyNotification setExpriedTime()    Sets the current record's "expriedTime" value
 * @method EmergencyNotification setActive()         Sets the current record's "active" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmergencyNotification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emergency_notification');
        $this->hasColumn('notificationId', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('content', 'string', 1000, array(
             'type' => 'string',
             'comment' => 'Nội dung thông báo',
             'length' => 1000,
             ));
        $this->hasColumn('createdTime', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => 'thời gian bắt đầu',
             ));
        $this->hasColumn('expriedTime', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => 'thời gian hết hạn',
             ));
        $this->hasColumn('active', 'int', 2, array(
             'type' => 'int',
             'comment' => '1 active',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}