<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MoResult', 'doctrine');

/**
 * BaseMoResult
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $id
 * @property bigint $mo_id
 * @property bigint $amount
 * @property bigint $userId
 * @property string $userName
 * @property string $mt_content
 * 
 * @method bigint   getId()         Returns the current record's "id" value
 * @method bigint   getMoId()       Returns the current record's "mo_id" value
 * @method bigint   getAmount()     Returns the current record's "amount" value
 * @method bigint   getUserId()     Returns the current record's "userId" value
 * @method string   getUserName()   Returns the current record's "userName" value
 * @method string   getMtContent()  Returns the current record's "mt_content" value
 * @method MoResult setId()         Sets the current record's "id" value
 * @method MoResult setMoId()       Sets the current record's "mo_id" value
 * @method MoResult setAmount()     Sets the current record's "amount" value
 * @method MoResult setUserId()     Sets the current record's "userId" value
 * @method MoResult setUserName()   Sets the current record's "userName" value
 * @method MoResult setMtContent()  Sets the current record's "mt_content" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMoResult extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mo_result');
        $this->hasColumn('id', 'bigint', 20, array(
             'type' => 'bigint',
             'primary' => true,
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('mo_id', 'bigint', 11, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => 'map voi id MoHistory',
             'length' => 11,
             ));
        $this->hasColumn('amount', 'bigint', 15, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 15,
             ));
        $this->hasColumn('userId', 'bigint', 15, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 15,
             ));
        $this->hasColumn('userName', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'username nap tien',
             'length' => 32,
             ));
        $this->hasColumn('mt_content', 'string', 256, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'tin nhan tra ve cho nguoi dung',
             'length' => 256,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}