<?php

/**
 * BaseExchangeAssetLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $requestId
 * @property bigint $requestUserId
 * @property string $requestUserName
 * @property integer $assetId
 * @property string $securityKey
 * @property integer $amount
 * @property integer $totalCash
 * @property timestamp $requestTime
 * @property timestamp $responseTime
 * @property string $description
 * @property int $accepted
 * @property string $request_topup_id
 * 
 * @method integer          getRequestId()        Returns the current record's "requestId" value
 * @method bigint           getRequestUserId()    Returns the current record's "requestUserId" value
 * @method string           getRequestUserName()  Returns the current record's "requestUserName" value
 * @method integer          getAssetId()          Returns the current record's "assetId" value
 * @method string           getSecurityKey()      Returns the current record's "securityKey" value
 * @method integer          getAmount()           Returns the current record's "amount" value
 * @method integer          getTotalCash()        Returns the current record's "totalCash" value
 * @method timestamp        getRequestTime()      Returns the current record's "requestTime" value
 * @method timestamp        getResponseTime()     Returns the current record's "responseTime" value
 * @method string           getDescription()      Returns the current record's "description" value
 * @method int              getAccepted()         Returns the current record's "accepted" value
 * @method string           getRequestTopupId()   Returns the current record's "request_topup_id" value
 * @method ExchangeAssetLog setRequestId()        Sets the current record's "requestId" value
 * @method ExchangeAssetLog setRequestUserId()    Sets the current record's "requestUserId" value
 * @method ExchangeAssetLog setRequestUserName()  Sets the current record's "requestUserName" value
 * @method ExchangeAssetLog setAssetId()          Sets the current record's "assetId" value
 * @method ExchangeAssetLog setSecurityKey()      Sets the current record's "securityKey" value
 * @method ExchangeAssetLog setAmount()           Sets the current record's "amount" value
 * @method ExchangeAssetLog setTotalCash()        Sets the current record's "totalCash" value
 * @method ExchangeAssetLog setRequestTime()      Sets the current record's "requestTime" value
 * @method ExchangeAssetLog setResponseTime()     Sets the current record's "responseTime" value
 * @method ExchangeAssetLog setDescription()      Sets the current record's "description" value
 * @method ExchangeAssetLog setAccepted()         Sets the current record's "accepted" value
 * @method ExchangeAssetLog setRequestTopupId()   Sets the current record's "request_topup_id" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExchangeAssetLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exchange_asset');
        $this->hasColumn('requestId', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('requestUserId', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('requestUserName', 'string', 32, array(
             'type' => 'string',
             'comment' => '',
             'length' => 32,
             ));
        $this->hasColumn('assetId', 'integer', 13, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => '',
             'length' => 13,
             ));
        $this->hasColumn('securityKey', 'string', 256, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Mã để cms kiểm tra có đúng request đổi thưởng từ người dùng không',
             'length' => 256,
             ));
        $this->hasColumn('amount', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Số lượng vật phẩm',
             'length' => 3,
             ));
        $this->hasColumn('totalCash', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'tổng giá trị xu ',
             'length' => 11,
             ));
        $this->hasColumn('requestTime', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => 'Thời điểm gửi yêu cầu',
             ));
        $this->hasColumn('responseTime', 'timestamp', null, array(
             'type' => 'timestamp',
             'comment' => '',
             ));
        $this->hasColumn('description', 'string', 256, array(
             'type' => 'string',
             'comment' => '',
             'length' => 256,
             ));
        $this->hasColumn('accepted', 'int', 2, array(
             'type' => 'int',
             'comment' => 'chấp nhận hoặc từ chối',
             'length' => 2,
             ));
        $this->hasColumn('request_topup_id', 'string', 256, array(
             'type' => 'string',
             'comment' => 'request Id lên topup',
             'length' => 256,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}