<?php

/**
 * BaseLogWeb
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $imei
 * @property string $agent
 * @property string $brownser
 * @property string $refer
 * @property string $ip
 * @property string $platform
 * 
 * @method string getImei()     Returns the current record's "imei" value
 * @method string getAgent()    Returns the current record's "agent" value
 * @method string getBrownser() Returns the current record's "brownser" value
 * @method string getRefer()    Returns the current record's "refer" value
 * @method string getIp()       Returns the current record's "ip" value
 * @method string getPlatform() Returns the current record's "platform" value
 * @method LogWeb setImei()     Sets the current record's "imei" value
 * @method LogWeb setAgent()    Sets the current record's "agent" value
 * @method LogWeb setBrownser() Sets the current record's "brownser" value
 * @method LogWeb setRefer()    Sets the current record's "refer" value
 * @method LogWeb setIp()       Sets the current record's "ip" value
 * @method LogWeb setPlatform() Sets the current record's "platform" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogWeb extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log_web');
        $this->hasColumn('imei', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'imei thiêt bị',
             'length' => 12,
             ));
        $this->hasColumn('agent', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'agent',
             'length' => 12,
             ));
        $this->hasColumn('brownser', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'trình duyệt',
             'length' => 12,
             ));
        $this->hasColumn('refer', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'nguồn',
             'length' => 12,
             ));
        $this->hasColumn('ip', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Link hình ảnh',
             'length' => 12,
             ));
        $this->hasColumn('platform', 'string', 32, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'loại thiết bị',
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}