<?php

/**
 * BaseUserOtpAuto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $otpId
 * @property bigint $userId
 * @property string $verifyCode
 * @property bigint $phoneNumber
 * @property integer $status
 * @property timestamp $expiredTime
 * 
 * @method integer     getOtpId()       Returns the current record's "otpId" value
 * @method bigint      getUserId()      Returns the current record's "userId" value
 * @method string      getVerifyCode()  Returns the current record's "verifyCode" value
 * @method bigint      getPhoneNumber() Returns the current record's "phoneNumber" value
 * @method integer     getStatus()      Returns the current record's "status" value
 * @method timestamp   getExpiredTime() Returns the current record's "expiredTime" value
 * @method UserOtpAuto setOtpId()       Sets the current record's "otpId" value
 * @method UserOtpAuto setUserId()      Sets the current record's "userId" value
 * @method UserOtpAuto setVerifyCode()  Sets the current record's "verifyCode" value
 * @method UserOtpAuto setPhoneNumber() Sets the current record's "phoneNumber" value
 * @method UserOtpAuto setStatus()      Sets the current record's "status" value
 * @method UserOtpAuto setExpiredTime() Sets the current record's "expiredTime" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserOtpAuto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_otp_auto');
        $this->hasColumn('otpId', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('userId', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('verifyCode', 'string', 32, array(
             'type' => 'string',
             'comment' => 'mã otp',
             'length' => 32,
             ));
        $this->hasColumn('phoneNumber', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => '0-chua su dung, 1: da gui ma xac thuc, 2 - da xu ly',
             'length' => 1,
             ));
        $this->hasColumn('expiredTime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}