<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PurchaseMoneyMissing', 'doctrine');

/**
 * BasePurchaseMoneyMissing
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $missId
 * @property integer $userId
 * @property string $userName
 * @property string $provider
 * @property string $cardSerial
 * @property string $cardPin
 * @property integer $cardValue
 * @property integer $toCash
 * @property integer $active
 * @property integer $admin_id
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer              getMissId()      Returns the current record's "missId" value
 * @method integer              getUserId()      Returns the current record's "userId" value
 * @method string               getUserName()    Returns the current record's "userName" value
 * @method string               getProvider()    Returns the current record's "provider" value
 * @method string               getCardSerial()  Returns the current record's "cardSerial" value
 * @method string               getCardPin()     Returns the current record's "cardPin" value
 * @method integer              getCardValue()   Returns the current record's "cardValue" value
 * @method integer              getToCash()      Returns the current record's "toCash" value
 * @method integer              getActive()      Returns the current record's "active" value
 * @method integer              getAdminId()     Returns the current record's "admin_id" value
 * @method sfGuardUser          getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method PurchaseMoneyMissing setMissId()      Sets the current record's "missId" value
 * @method PurchaseMoneyMissing setUserId()      Sets the current record's "userId" value
 * @method PurchaseMoneyMissing setUserName()    Sets the current record's "userName" value
 * @method PurchaseMoneyMissing setProvider()    Sets the current record's "provider" value
 * @method PurchaseMoneyMissing setCardSerial()  Sets the current record's "cardSerial" value
 * @method PurchaseMoneyMissing setCardPin()     Sets the current record's "cardPin" value
 * @method PurchaseMoneyMissing setCardValue()   Sets the current record's "cardValue" value
 * @method PurchaseMoneyMissing setToCash()      Sets the current record's "toCash" value
 * @method PurchaseMoneyMissing setActive()      Sets the current record's "active" value
 * @method PurchaseMoneyMissing setAdminId()     Sets the current record's "admin_id" value
 * @method PurchaseMoneyMissing setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePurchaseMoneyMissing extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('purchase_money_missing');
        $this->hasColumn('missId', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('userId', 'integer', 11, array(
             'type' => 'integer',
             'comment' => 'user nap',
             'length' => 11,
             ));
        $this->hasColumn('userName', 'string', 32, array(
             'type' => 'string',
             'comment' => 'user nap',
             'length' => 32,
             ));
        $this->hasColumn('provider', 'string', 11, array(
             'type' => 'string',
             'comment' => 'mã nhà cũng cấp',
             'length' => 11,
             ));
        $this->hasColumn('cardSerial', 'string', 32, array(
             'type' => 'string',
             'comment' => 'serial',
             'length' => 32,
             ));
        $this->hasColumn('cardPin', 'string', 32, array(
             'type' => 'string',
             'comment' => 'Pin thẻ',
             'length' => 32,
             ));
        $this->hasColumn('cardValue', 'integer', 32, array(
             'type' => 'integer',
             'comment' => 'mệnh giá tiền nạp',
             'length' => 32,
             ));
        $this->hasColumn('toCash', 'integer', 11, array(
             'type' => 'integer',
             'comment' => 'Số cash được cộng',
             'length' => 11,
             ));
        $this->hasColumn('active', 'integer', 2, array(
             'type' => 'integer',
             'comment' => 'Trạng thái giao dịch',
             'length' => 2,
             ));
        $this->hasColumn('admin_id', 'integer', 11, array(
             'type' => 'integer',
             'comment' => 'admin tạo',
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'admin_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}