<?php

/**
 * BaseTaiGame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $OS
 * @property string $link_tai
 * @property string $file_down
 * @property integer $is_direct
 * @property integer $count
 * @property string $version_build
 * @property string $platform_icon
 * @property integer $status
 * 
 * @method string  getOS()            Returns the current record's "OS" value
 * @method string  getLinkTai()       Returns the current record's "link_tai" value
 * @method string  getFileDown()      Returns the current record's "file_down" value
 * @method integer getIsDirect()      Returns the current record's "is_direct" value
 * @method integer getCount()         Returns the current record's "count" value
 * @method string  getVersionBuild()  Returns the current record's "version_build" value
 * @method string  getPlatformIcon()  Returns the current record's "platform_icon" value
 * @method integer getStatus()        Returns the current record's "status" value
 * @method TaiGame setOS()            Sets the current record's "OS" value
 * @method TaiGame setLinkTai()       Sets the current record's "link_tai" value
 * @method TaiGame setFileDown()      Sets the current record's "file_down" value
 * @method TaiGame setIsDirect()      Sets the current record's "is_direct" value
 * @method TaiGame setCount()         Sets the current record's "count" value
 * @method TaiGame setVersionBuild()  Sets the current record's "version_build" value
 * @method TaiGame setPlatformIcon()  Sets the current record's "platform_icon" value
 * @method TaiGame setStatus()        Sets the current record's "status" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaiGame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tai_game');
        $this->hasColumn('OS', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => '1: andoird, 2: IOS, 3: windown',
             'length' => 12,
             ));
        $this->hasColumn('link_tai', 'string', 256, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Link tai game store',
             'length' => 256,
             ));
        $this->hasColumn('file_down', 'string', 256, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Link tai truc tiếp trên web',
             'length' => 256,
             ));
        $this->hasColumn('is_direct', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => '0: tai truc tiep qua store, 1: tai file apk',
             'length' => 1,
             ));
        $this->hasColumn('count', 'integer', 6, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'Số lượt tải',
             'length' => 6,
             ));
        $this->hasColumn('version_build', 'string', 256, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'version game',
             'length' => 256,
             ));
        $this->hasColumn('platform_icon', 'string', 256, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Ảnh banner tải game',
             'length' => 256,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => '0: inactive, 1: active',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}