<?php

/**
 * BaseVtActionLogs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ip
 * @property string $action
 * @property string $description
 * @property bigint $actor_id
 * @property string $model
 * @property string $record_id
 * @property sfGuardUser $sfGuardUser
 * 
 * @method string       getIp()          Returns the current record's "ip" value
 * @method string       getAction()      Returns the current record's "action" value
 * @method string       getDescription() Returns the current record's "description" value
 * @method bigint       getActorId()     Returns the current record's "actor_id" value
 * @method string       getModel()       Returns the current record's "model" value
 * @method string       getRecordId()    Returns the current record's "record_id" value
 * @method sfGuardUser  getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method VtActionLogs setIp()          Sets the current record's "ip" value
 * @method VtActionLogs setAction()      Sets the current record's "action" value
 * @method VtActionLogs setDescription() Sets the current record's "description" value
 * @method VtActionLogs setActorId()     Sets the current record's "actor_id" value
 * @method VtActionLogs setModel()       Sets the current record's "model" value
 * @method VtActionLogs setRecordId()    Sets the current record's "record_id" value
 * @method VtActionLogs setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtActionLogs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vt_action_logs');
        $this->hasColumn('ip', 'string', 50, array(
             'type' => 'string',
             'comment' => 'Ip của admin',
             'length' => 50,
             ));
        $this->hasColumn('action', 'string', 20, array(
             'type' => 'string',
             'comment' => 'ten hanh dong ACCESS, ADD, UPDATE, DELETE, ACTIVE, DEACTIVE, REQUEST_APPROVE, APPROVE, DENY, SIGN',
             'length' => 20,
             ));
        $this->hasColumn('description', 'string', 256, array(
             'type' => 'string',
             'comment' => 'Nội dung thực hiện',
             'length' => 256,
             ));
        $this->hasColumn('actor_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('model', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên bảng tác động (1 bảng cho mỗi dòng)',
             'length' => 50,
             ));
        $this->hasColumn('record_id', 'string', 20, array(
             'type' => 'string',
             'comment' => 'ID bản ghi bị tác động',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'actor_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}