<?php

/**
 * BaseNotify
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $content
 * @property boolean $status
 * 
 * @method string  getContent() Returns the current record's "content" value
 * @method boolean getStatus()  Returns the current record's "status" value
 * @method Notify  setContent() Sets the current record's "content" value
 * @method Notify  setStatus()  Sets the current record's "status" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotify extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notify');
        $this->hasColumn('content', 'string', 6000, array(
             'type' => 'string',
             'comment' => 'Noi dung thong bao',
             'length' => 6000,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'comment' => '0: deactive, 1:active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}