<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AddMoney', 'doctrine');

/**
 * BaseAddMoney
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userId
 * @property integer $addCash
 * @property integer $addGold
 * @property string $description
 * @property integer $admin_id
 * @property integer $status
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getUserId()      Returns the current record's "userId" value
 * @method integer     getAddCash()     Returns the current record's "addCash" value
 * @method integer     getAddGold()     Returns the current record's "addGold" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method integer     getAdminId()     Returns the current record's "admin_id" value
 * @method integer     getStatus()      Returns the current record's "status" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method AddMoney    setUserId()      Sets the current record's "userId" value
 * @method AddMoney    setAddCash()     Sets the current record's "addCash" value
 * @method AddMoney    setAddGold()     Sets the current record's "addGold" value
 * @method AddMoney    setDescription() Sets the current record's "description" value
 * @method AddMoney    setAdminId()     Sets the current record's "admin_id" value
 * @method AddMoney    setStatus()      Sets the current record's "status" value
 * @method AddMoney    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAddMoney extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('add_money');
        $this->hasColumn('userId', 'integer', 11, array(
             'type' => 'integer',
             'comment' => 'user id nạp tiền',
             'length' => 11,
             ));
        $this->hasColumn('addCash', 'integer', 11, array(
             'type' => 'integer',
             'comment' => 'Số cash được cộng',
             'length' => 11,
             ));
        $this->hasColumn('addGold', 'integer', 11, array(
             'type' => 'integer',
             'comment' => 'Số gold được cộng',
             'length' => 11,
             ));
        $this->hasColumn('description', 'string', 256, array(
             'type' => 'string',
             'comment' => 'Lý do cộng tiền',
             'length' => 256,
             ));
        $this->hasColumn('admin_id', 'integer', 11, array(
             'type' => 'integer',
             'comment' => 'admin id cộng tiền',
             'length' => 11,
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'comment' => 'Trạng thái giao dịch: 0 tạo mới, 1: cộng tiền thành công',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'admin_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}