<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CardProvider', 'doctrine');

/**
 * BaseCardProvider
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $providerId
 * @property string $providerCode
 * @property stringh $providerName
 * @property string $description
 * @property integer $active
 * @property string $telcoPercent
 * @property string $valuePercent
 * 
 * @method integer      getProviderId()   Returns the current record's "providerId" value
 * @method string       getProviderCode() Returns the current record's "providerCode" value
 * @method stringh      getProviderName() Returns the current record's "providerName" value
 * @method string       getDescription()  Returns the current record's "description" value
 * @method integer      getActive()       Returns the current record's "active" value
 * @method string       getTelcoPercent() Returns the current record's "telcoPercent" value
 * @method string       getValuePercent() Returns the current record's "valuePercent" value
 * @method CardProvider setProviderId()   Sets the current record's "providerId" value
 * @method CardProvider setProviderCode() Sets the current record's "providerCode" value
 * @method CardProvider setProviderName() Sets the current record's "providerName" value
 * @method CardProvider setDescription()  Sets the current record's "description" value
 * @method CardProvider setActive()       Sets the current record's "active" value
 * @method CardProvider setTelcoPercent() Sets the current record's "telcoPercent" value
 * @method CardProvider setValuePercent() Sets the current record's "valuePercent" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCardProvider extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('card_provider');
        $this->hasColumn('providerId', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 10,
             ));
        $this->hasColumn('providerCode', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('providerName', 'stringh', 20, array(
             'type' => 'stringh',
             'notnull' => true,
             'comment' => 'Tên nhà cung cấp',
             'length' => 20,
             ));
        $this->hasColumn('description', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Mô tả',
             'length' => 20,
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'comment' => 'Active = 1',
             'length' => 1,
             ));
        $this->hasColumn('telcoPercent', 'string', 5, array(
             'type' => 'string',
             'default' => 1,
             'comment' => 'Tỉ lệ game nhận được từ nhà mạng',
             'length' => 5,
             ));
        $this->hasColumn('valuePercent', 'string', 5, array(
             'type' => 'string',
             'default' => 1,
             'comment' => 'Tỉ lệ Ken nhận được',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}