<?php

/**
 * BaseWebContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $image
 * @property string $content
 * @property string $title
 * @property integer $status
 * @property integer $type
 * @property integer $is_hot
 * 
 * @method string     getImage()   Returns the current record's "image" value
 * @method string     getContent() Returns the current record's "content" value
 * @method string     getTitle()   Returns the current record's "title" value
 * @method integer    getStatus()  Returns the current record's "status" value
 * @method integer    getType()    Returns the current record's "type" value
 * @method integer    getIsHot()   Returns the current record's "is_hot" value
 * @method WebContent setImage()   Sets the current record's "image" value
 * @method WebContent setContent() Sets the current record's "content" value
 * @method WebContent setTitle()   Sets the current record's "title" value
 * @method WebContent setStatus()  Sets the current record's "status" value
 * @method WebContent setType()    Sets the current record's "type" value
 * @method WebContent setIsHot()   Sets the current record's "is_hot" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('web_content');
        $this->hasColumn('image', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Link hình ảnh',
             'length' => 12,
             ));
        $this->hasColumn('content', 'string', 8000, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Nội dung',
             'length' => 8000,
             ));
        $this->hasColumn('title', 'string', 512, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Tieu de',
             'length' => 512,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => '0 tạo mới, 1 active',
             'length' => 1,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => '0: tin tức, 1 sự kiện',
             'length' => 1,
             ));
        $this->hasColumn('is_hot', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => '1: top hot',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}