<?php

/**
 * BaseUserVerify
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $user_id
 * @property string $verify_code
 * @property integer $expried_time
 * @property string $mo_id
 * @property string $msisdn
 * @property int $type
 * 
 * @method bigint     getUserId()       Returns the current record's "user_id" value
 * @method string     getVerifyCode()   Returns the current record's "verify_code" value
 * @method integer    getExpriedTime()  Returns the current record's "expried_time" value
 * @method string     getMoId()         Returns the current record's "mo_id" value
 * @method string     getMsisdn()       Returns the current record's "msisdn" value
 * @method int        getType()         Returns the current record's "type" value
 * @method UserVerify setUserId()       Sets the current record's "user_id" value
 * @method UserVerify setVerifyCode()   Sets the current record's "verify_code" value
 * @method UserVerify setExpriedTime()  Sets the current record's "expried_time" value
 * @method UserVerify setMoId()         Sets the current record's "mo_id" value
 * @method UserVerify setMsisdn()       Sets the current record's "msisdn" value
 * @method UserVerify setType()         Sets the current record's "type" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserVerify extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_otp');
        $this->hasColumn('user_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'comment' => '',
             'length' => 20,
             ));
        $this->hasColumn('verify_code', 'string', 32, array(
             'type' => 'string',
             'comment' => 'Mệnh giá thẻ cào hoặc giá niêm yết của hiện vật',
             'length' => 32,
             ));
        $this->hasColumn('expried_time', 'integer', 13, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => '',
             'length' => 13,
             ));
        $this->hasColumn('mo_id', 'string', 256, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'map voi bang mo_log',
             'length' => 256,
             ));
        $this->hasColumn('msisdn', 'string', 15, array(
             'type' => 'string',
             'comment' => '',
             'length' => 15,
             ));
        $this->hasColumn('type', 'int', 2, array(
             'type' => 'int',
             'comment' => 'kiểu otp: 0 xác thực tai khoan, 1 reset mật khẩu',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}