generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           WebContent
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          web_content
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Thống kê nội dung web site
        display: [title, image, content, status, type, is_hot, created_at]
        object_actions: {}
        batch_actions: {}
      filter:
        display: [title, content, type]
      form:
        class: bkManageWebContentFormAdmin
        display: [title, content, image, status, type, is_hot]
      edit:    ~
      new:     ~
