generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           GiftCode
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gift_code
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        cashValue: { label: Ken }
        goldValue: { label: Xu }
        adminId: { label: Người tạo giftcode }
      list:
        title: Danh sách gift code
        display: [giftEventId, userId, code, cashValue, goldValue,ip,  reuseable, status,adminId,description]
        title: Danh sách gift code
        object_actions:
#          _edit: {label: Chi tiết}
          _delete: ~
      filter:
        class: gvManageGiftCodeFormFiltersAdmin
        display: [userName]
      form:
        display: [giftEventId, userName, userId,  expiredTime, description]
        class: gvManageGiftCodeFormAdmin
      edit:    ~
      new:     ~
