<?php

/**
 * AddMoneyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddMoneyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AddMoneyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AddMoney');
    }
}