<?php

/**
 * AddMoney
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AddMoney extends BaseAddMoney
{
    public function getStatusView(){
        $i18n = sfContext::getInstance()->getI18N();
        $arr_status = array("" => $i18n->__("Tất cả"), 0 => $i18n->__("Tạo mới"), 1 => $i18n->__("Thành công") ,2 => $i18n->__("Thất bại") );
        return $arr_status[$this->getStatus()];
    }
}