<?php

/**
 * BlackListUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlackListUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlackListUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlackListUser');
    }
}