<?php

/**
 * EmergencyNotificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmergencyNotificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmergencyNotificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmergencyNotification');
    }
}