<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }

    public static  function getNewestEvent($status = null)
    {
        $sql =   EventTable::getInstance()->createQuery('a')
            ->select('*');
        if(isset($status)){
            $sql->where('a.status = ?', $status);
        }
//        $sql->orderBy('a.starttime desc');
        return $sql->fetchArray();
    }
}