<?php

/**
 * ExchangeAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExchangeAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExchangeAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExchangeAsset');
    }
}