<?php

/**
 * ExchangeAssetLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExchangeAssetLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExchangeAssetLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExchangeAssetLog');
    }
}