<?php

/**
 * ExchangeAssetRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExchangeAssetRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExchangeAssetRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExchangeAssetRequest');
    }
    public static function checkRequest($securityKey, $requestId)
    {
        return self::getInstance()->createQuery('a')
            ->select('a.*')
            ->where('a.securityKey = ?', $securityKey)
            ->andWhere('a.requestId = ?', $requestId)
            ->andWhere('a.status = ?', VtCommonEnum::NUMBER_ZERO)
            ->andWhere('a.request_topup_id is null')
            ->fetchOne();
    }
    public static function getTotalRevenueByDate($values = null)
    {
        $query = ExchangeAssetRequestTable::getInstance()->createQuery('a');
        $query->select("sum(a.totalParValue) as sum_money, DATE(a.created_at) as purchase_date");
        $query->groupBy("DATE(a.created_at)");
        $query->orderBy("a.created_at asc");
        $query->where("a.status = 1");
        $query->andWhere("a.created_at > ?",  Date("Y-m-d H:i:s", time() - 86400* 7));
        return $query->fetchArray();
    }
    public static function getTotalRevenue($values = null)
    {
        $query = ExchangeAssetRequestTable::getInstance()->createQuery('a');
        $query->select("sum(a.totalParValue) as sum_money");
        $query->orderBy("a.created_at asc");
        $query->where("a.status = 1");
        return $query->fetchOne()->sum_money;
    }
    public static function getSumRequestByDay($userId)
    {
        $query = ExchangeAssetRequestTable::getInstance()->createQuery('a');
        $query->select("sum(a.totalParValue) as sum_money");
        $query->where("a.requestUserId = ?" . $userId);
        $query->andWhere("a.created_at > ?",  date("Y-m-d"));
        return $query->fetchOne();
    }


}