<?php

/**
 * GameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Game');
    }
    public static  function getListGame($gameId = null)
    {
        $sql =   GameTable::getInstance()->createQuery('a')
            ->select('a.gameid, a.name, a.description')
            ->where('status = 1');
        if($gameId){
            $sql->andWhere("a.gameid =?", $gameId);
        }
        return $sql->fetchArray();
    }
    public static function getListGameForSelectBox()
    {
        $i18n = sfContext::getInstance()->getI18N();
        $listType[""] = $i18n->__("Tất cả");
        $arrType = GameTable::getInstance()->createQuery('a')
            ->select('a.gameid, a.name')->fetchArray();
        foreach($arrType as $valType){
            $listType[$valType['gameid']] = $valType['name'];
        }
        return $listType;
    }

    public function addActiveGameQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('Game j');
        }

        $alias = $q->getRootAlias();

        $q->where($alias .'.status = 1');

        return $q;
    }

    public function getActiveGameQuery()
    {
        $q = Doctrine_Query::create()
            ->from('Game j');

        return Doctrine::getTable('Game')->addActiveGameQuery($q);
    }

    public static  function getAllRecord()
    {
        $itemNumber = sfConfig::get('app_wap_item_list_number') != null ? sfConfig::get('app_wap_item_list_number') : 4;
        $sql =   GameTable::getInstance()->createQuery('a')
            ->select('*')
            ->where('a.status = 1')
            ->limit($itemNumber);
        return $sql->fetchArray();
    }

    public static  function getTotalRecord()
    {
        $sql =   GameTable::getInstance()->createQuery('a')
            ->select('*')
            ->where('a.status = 1');
        return $sql->count();
    }

    public static  function getNewestRecord()
    {
        $itemNumber = sfConfig::get('app_wap_item_list_number') != null ? sfConfig::get('app_wap_item_list_number') : 4;
        $sql =   GameTable::getInstance()->createQuery('a')
            ->select('*')
            ->where('a.status = 1')
            ->limit($itemNumber);
        return $sql->fetchArray();
    }
}