<?php

/**
 * GiftCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GiftCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GiftCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GiftCode');
    }
    public static function getSumGiftUser(){
        return GiftCodeTable::getInstance()->createQuery('u')
            ->select ('SUM(u.cashValue) AS sum_cash, SUM(u.goldValue) AS sum_gold')
            ->where("status = 1")
            ->fetchArray();
    }
}