<?php

/**
 * GiftEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GiftEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GiftEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GiftEvent');
    }

    public static function getEventById($id)
    {
        return GiftEventTable::getInstance()->createQuery('a')
            ->select ("a.*")
            ->where("a.giftEventId = ?",$id)
            ->fetchOne();
    }
}