<?php

/**
 * LoggedInLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoggedInLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoggedInLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LoggedInLog');
    }

    public static function getPlayUserInday($created_at)
    {
        return LoggedInLogTable::getInstance()->createQuery('a')
            ->select ('count(DISTINCT a.userId), date(a.loggedInTime)')
            ->groupby("date(a.loggedInTime)")
            ->where("a.loggedInTime > ?", $created_at)
            ->fetchArray();
    }
}