<?php

/**
 * LogPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LogPayment extends BaseLogPayment
{
    public function getPinCardView(){
        $admin = sfContext::getInstance()->getUser()->hasCredential('admin');
        if ($admin) {
            return $this->getPinCard();
        } else {
            return VtHelper::truncate( $this->getPinCard(), 6, "****");
        }
    }
}