<?php

/**
 * LogWebTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogWebTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogWebTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogWeb');
    }
}