<?php

/**
 * LuckyWheelChanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LuckyWheelChanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LuckyWheelChanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LuckyWheelChance');
    }
}