<?php

/**
 * LuckyWheelItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LuckyWheelItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LuckyWheelItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LuckyWheelItem');
    }
}