<?php

/**
 * MoResultTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MoResultTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MoResultTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MoResult');
    }
}