<?php

/**
 * NotifyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotifyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotifyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Notify');
    }
    public static  function getNewestNofify($status = null)
    {
        $sql =   NotifyTable::getInstance()->createQuery('a')
            ->select('a.id, a.content')
            ->orderBy(".status desc, created_at desc");
        if(isset($status)){
            $sql->where('status = ?', $status);
        }
        return $sql->fetchOne();
    }
}