<?php

/**
 * OnlineLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OnlineLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OnlineLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OnlineLog');
    }
    public static  function getOnlineLog($insertedtime = null, $option = null)
    {
        $sql=   OnlineLogTable::getInstance()->createQuery('a')
            ->select('a.logId, a.peakData, a.insertedTime');
        if($option == 1 || $option == 2 || $option == 6){
            $sql->where('a.insertedTime >= ?' , date("Y-m-d H:i:s", time() - 3600 * $option));
        } else if($option == 24){
            $sql->where('Date(insertedTime) = ?' , date("Y-m-d", time()));
            $sql->andWhere('a.logId % 4 = 1');
        }
        if ($insertedtime && $insertedtime != date("Y-m-d", time())){
            $sql->where('Date(insertedTime) = ?' , $insertedtime);
            $sql->andWhere('a.logId % 4 = 1');
        }
       return  $sql->orderBy('a.insertedTime desc')
            ->fetchArray();
    }
}