<?php

/**
 * ProviderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProviderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProviderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Provider');
    }
    public static function getListProviderForSelectBox()
    {
        $i18n = sfContext::getInstance()->getI18N();
        $listType[""] = $i18n->__("Tất cả");
        $arrType = ProviderTable::getInstance()->createQuery('a')
            ->select('a.id, a.code')->fetchArray();
        foreach($arrType as $valType){
            $listType[$valType['id']] = $valType['code'];
        }
        return $listType;
    }
}