<?php

/**
 * UserVerifyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserVerifyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserVerifyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserVerify');
    }
}