<?php

/**
 * UserOtpAuto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserOtpAuto extends BaseUserOtpAuto
{
    public function getPhoneNumberView()
    {
        $admin = sfContext::getInstance()->getUser()->hasCredential('admin');
        if ($admin) {
            return $this->getPhoneNumber();
        } else {
            return VtHelper::truncate( $this->getPhoneNumber(), 8, "*");
        }
    }
}