<?php

/**
 * UserOtpAutoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserOtpAutoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserOtpAutoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserOtpAuto');
    }

    public function checkUserOtpAuto($otp)
    {
        return UserOtpAutoTable::getInstance()->createQuery('a')
            ->select("a.*")
            ->where("a.verifyCode = ?",  $otp)
            ->andWhere("a.expiredTime > ?", date("Y-m-d H:i:s", time()))
            ->andWhere("a.status = 0")
            ->andWhere("a.phoneNumber is null")
            ->fetchOne();
    }
}