<?php

/**
 * UserOTPTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserOTPTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserOTPTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserOTP');
    }
}