<?php

/**
 * UserInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserInfo extends BaseUserInfo
{
    public function getPhoneNumberView()
    {
        $admin = sfContext::getInstance()->getUser()->hasCredential('admin');
        if ($admin) {
            return $this->getVerifiedPhone();
        } else {
            return VtHelper::truncate( $this->getVerifiedPhone(), 8, "*");
        }
    }
    public function getUsernameView()
    {
        $admin = sfContext::getInstance()->getUser()->hasCredential('admin');
        if ($admin) {
            return $this->getUsername();
        } else {
            return VtHelper::truncate( $this->getUsername(), 3, "*");
        }
    }
}