<?php

/**
 * UserResetPWTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserResetPWTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserResetPWTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserResetPW');
    }
}