<?php

/**
 * UserOTP
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserOTP extends BaseUserOTP
{
    public function getStatusView()
    {
        return $this->status == 0 ? "Chưa sử dung" : "Đã sử dụng";
    }
    public function getTypeView(){
        $i18n = sfContext::getInstance()->getI18N();
        $arr_status = array("0" => $i18n->__("Xác thực"), 1 => $i18n->__("Xác thực"), 1 => $i18n->__("Reset Mật khẩu") ,2 => $i18n->__("Hủy xác thực") );
        return $arr_status[$this->getStatus()];
    }

}