<?php

/**
 * WebContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebContent');
    }

    public static  function getNewestContent($status = null, $type = null)
    {
        $sql =   WebContentTable::getInstance()->createQuery('a')
            ->select('*');
        if(isset($type)){
            $sql->where('a.type = ?', $type);
        }
        if(isset($status)){
            $sql->andWhere('a.status = ?', $status);
        }
        return $sql->fetchOne();
    }

    public static  function getAllContent($type = null)
    {

        $sql =   WebContentTable::getInstance()->createQuery('a')
            ->select('*');
        if(isset($type)){
            $sql->where('a.type = ?', $type);
        }
        return $sql->fetchOne();
    }

    public static  function getNewestRecord($type = null)
    {
        $itemNumber = sfConfig::get('app_wap_item_list_number') != null ? sfConfig::get('app_wap_item_list_number') : 4;
        $sql =   WebContentTable::getInstance()->createQuery('a')
            ->select('*')
            ->where('a.status = 1')
            ->andWhere('a.type = ?', $type)
            ->orderBy('a.created_at desc')
            ->limit($itemNumber);
        return $sql->fetchArray();
    }

    public static  function getAllRecord($type = null)
    {
        $itemNumber = sfConfig::get('app_wap_item_list_number') != null ? sfConfig::get('app_wap_item_list_number') : 4;
        $sql =   WebContentTable::getInstance()->createQuery('a')
            ->select('*')
            ->where('a.status = 1')
            ->andWhere('a.type = ?', $type)
            ->orderBy('a.created_at desc')
            ->limit($itemNumber);
        return $sql->fetchArray();
    }

    public static  function getTotalRecord($type = null)
    {
        $sql =   WebContentTable::getInstance()->createQuery('a')
            ->select('*')
            ->where('a.status = 1')
            ->andWhere('a.type = ?', $type)
            ->orderBy('a.created_at desc');
        return $sql->count();
    }

    public function retrieveActiveWebContent(Doctrine_Query $q)
    {
        return $this->addActiveWebContentQuery($q)->fetchOne();
    }

    public function getActiveWebContent($max = 1)
    {
        $q = $this->getActiveWebContentQuery()
            ->limit($max);

        return $q->execute();
    }

    public function getDefaultWebContent($max = 4)
    {
        $q = $this->getActiveWebContentQuery()
            ->limit($max);

        return $q->execute();
    }

    public function countActiveWebContent($type = null)
    {
        return $this->getActiveWebContentQuery($type)->count();
    }

    public function addActiveWebContentQuery(Doctrine_Query $q = null, $type = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('WebContent j');
        }

        $alias = $q->getRootAlias();

        $q->where($alias .'.status = 1')->andWhere($alias . '.type = ?', $type )
            ->addOrderBy($alias . '.created_at DESC');

        return $q;
    }

    public function getActiveWebContentQuery($type = null)
    {
        $q = Doctrine_Query::create()
            ->from('WebContent j');

        return Doctrine::getTable('WebContent')->addActiveWebContentQuery($q, $type);
    }

    public static function getObjectBySlug($slug)
    {
        $sql =   WebContentTable::getInstance()->createQuery('a')
            ->select('*')
            ->where('a.slug = ?', $slug)
            ->orderBy('a.created_at desc');
        return $sql->fetchOne();
    }

}