<?php

/**
 * WebContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebContent');
    }

    public static  function getNewestContent($status = null, $type = null)
    {
        $sql =   WebContentTable::getInstance()->createQuery('a')
            ->select('*');
        if(isset($type)){
            $sql->where('a.type = ?', $type);
        }
        if(isset($status)){
            $sql->andWhere('a.status = ?', $status);
        }
        return $sql->fetchOne();
    }

    public static  function getAllContent($type = null)
    {

        $sql =   WebContentTable::getInstance()->createQuery('a')
            ->select('*');
        if(isset($type)){
            $sql->where('a.type = ?', $type);
        }
        return $sql->fetchOne();
    }
}