<?php

/**
 * WebContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebContent');
    }
}