generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           LoggedInLog
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          logged_in_log
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        deviceId: {label: IME}
        remoteIp: {label: Địa chỉ Ip}
        deviceInfo: {label: Thông tin thiết bị}
      list:
        title: Log đăng nhập
        display: [userId, userName, loggedInTime, deviceId, deviceInfo, remoteIp, clientType, packageName, versionCode, versionBuild, ipLocked, reloggedIn]
        sort: [loggedInTime, 'desc']
        actions: {}
        object_actions: {}
        batch_actions: {}
      filter:
        class: gvManageLoggedInLogFormFiltersAdmin
        display: [userId, userName,deviceId, remoteIp ]
      form:    ~
      edit:    ~
      new:     ~
