<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    public function getUserByUsername($username, $is_active = 1) {
        $q = $this->createQuery()
            ->where('username = ?', $username)
            ->addWhere('is_active = ?', $is_active);

        return $q->fetchOne();
    }
    public function getSortUsernameAscList(Doctrine_Query $q)
    {
        return $q->orderBy('username');
    }
    public static function queryListUserActive(){
        return sfGuardUserTable::getInstance()->createQuery()
            ->select('username, id')
            ->where('is_active =?', VtCommonEnum::NUMBER_ONE)
            ->orderBy('username ASC');
    }
    public function setUnLockUser($username) {
        $q = $this->createQuery()
            ->update('sfGuardUser u')
            ->set('u.is_lock_signin', '?', 0)
            ->set('u.locked_time', 'NULL')
            ->where('u.username = ?', $username);

        return $q->execute();
    }

    public function updateUserLog($username, $time) {
        $q = $this->createQuery()
            ->update()
            ->set('is_lock_signin', '?', 1)
            ->set('locked_time', '?', $time)
            ->where('username = ?', $username);

        return $q->execute();
    }
}