<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    public function getUserByUsername($username, $is_active = 1) {
        $q = $this->createQuery()
            ->where('username = ?', $username)
            ->addWhere('is_active = ?', $is_active);

        return $q->fetchOne();
    }
    public function getSortUsernameAscList(Doctrine_Query $q)
    {
        return $q->orderBy('username');
    }
}