generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           LogWeb
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          log_web
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        actions: {}
        object_actions: {}
        batch_actions: {}
      filter:
        display: [ip, refer, platform]
      form:    ~
      edit:    ~
      new:     ~
