generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           partner
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          partner
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _list: {label: Quay trở lại danh sách}
        _save: {label: Lưu}
        _delete: {label: Xóa}
        _edit: {label: Chi tiết}
      fields:  ~
      list:
        title : Danh sách đối tác
        display: [partnername, smsnumber, username, accesskey1, accesskey2]
        object_actions:
          _edit: {label: Chi tiết}
          _delete: ~
      filter:
        display: [partnername, username]
      form:
        display: [partnername, smsnumber, username, password, accesskey1, accesskey2]
      edit:
        title: Chỉnh sửa đối tác
      new:
        title: Tạo mới đối tác
