generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           partner
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          partner
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [partnername, username]
      filter:
        display: [partnername, username]
      form:    ~
      edit:    ~
      new:     ~
