generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           ClientType
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          client_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _list: {label: Quay trở lại danh sách}
        _save: {label: Lưu}
        _delete: {label: Xóa}
        _edit: {label: Chi tiết}
      fields:  ~
      list:
        title : Danh sách hệ điều hành
        object_actions:
          _edit: {label: Chi tiết}
          _delete: ~
      filter:  ~
      form:    ~
      edit:
        title: Chỉnh sửa hệ điều hành
      new:
        title: Tạo mới hệ điều hành
