all:
  slave:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=124.158.7.138;dbname=bigken'
      username: bigken
      password: mySql!Bk16@
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=124.158.7.138;dbname=bigken'
      username: bigken
      password: mySql!Bk16@
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }