generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           Provider
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          provider
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Danh sách nhà mạng
        display: ~
        actions:
          _new: {label: Thêm mới}
        object_actions:
          _edit: ~
      edit:
        title: Chỉnh sửa nhà mạng
      new:
        title: Thêm mới nhà mạng
      filter:
        class:  gvManageProviderFormFilter
        display: ~
      form:    ~
