generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           OnlineLog
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          online_log
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        insertedtime: {label: Ngày }
      list:
        title: Thống kê CCU
        actions: {}
        object_actions: {}
        batch_actions: {}
      filter:
        class: gvManageOnlineLogFormFiltersAdmin
        display: [insertedtime, option]
      form:    ~
      edit:    ~
      new:     ~
