## YAML Template.
---
indexSuccess:
  metas:
    title: Thống kê chi tiết nạp tiền
  stylesheets:
    - bootstrapDaterangepickerMaster/daterangepicker-bs2.css

  javascripts:
    - bootstrapDaterangepickerMaster/moment.min.js
    - bootstrapDaterangepickerMaster/daterangepicker.js