generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           LogPayment
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          log_payment
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        money: {label: Mệnh giá thẻ}
        pin_card: {label: Mã thẻ cào}
      list:
        title: Quản lý lịch sử nạp thẻ
        sort: [created_at, desc]
        display: [userid, seria, pin_card_view, money,  message, providerId,status, created_at, updated_at]
        actions: {}
        object_actions: {}
        batch_actions: {}
      filter:
        class: bkManageLogPaymentFormFiltersAdmin
        display: [userid, seria, pin_card,  money, providerId, status]
      form:    ~
      edit:    ~
      new:     ~
