generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           CardProvider
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          card_provider
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [providerCode, providerName, description, active, telcoPercent, valuePercent]
        title: Danh sách nhà cung cấp thẻ
        object_actions: {}
        actions: {}
        batch_actions: {}
      filter:
        display: [providerCode]
        class: gvManageCardProviderFormFiltersAdmin
      form:    ~
      edit:    ~
      new:     ~
