generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           MoneyLog
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          money_log
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: Lịch sử giao dịch
        display: [display_name, userId, userName, lastCash, changeCash, currentCash, lastGold, changeGold, currentGold, transaction_view, taxPercent, taxValue, gameId, insertedTime, description]
        actions: {}
        object_actions: {}
        batch_actions: {}
      filter:
        class: gvManageMoneyLogtFormFiltersAdmin
        display: [user_id, user_name, type, gameId, insertedTime]
      form:    ~
      edit:    ~
      new:     ~
