generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           SystemProperties
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          system_properties
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        object_actions: {}
        batch_actions: {}
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
