generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           game
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          game
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Quản lý game
        display:  ~
        actions: {}
        object_actions: {}
      filter:
        class: gvManageGameFormFilter
        display:  ~
      form:    ~
      edit:    ~
      new:     ~
