## YAML Template.
---
indexSuccess:
  metas:
    title: Quản lý game
  stylesheets:
    - bootstrapDaterangepickerMaster/daterangepicker-bs2.css

  javascripts:
    - jquery.min.js
    - bootstrapDaterangepickerMaster/moment.min.js
    - bootstrapDaterangepickerMaster/daterangepicker.js