## YAML Template.
---
indexSuccess:
  metas:
    title: Doanh thu thẻ nạp
  stylesheets:
    - bootstrapDaterangepickerMaster/daterangepicker-bs2.css

  javascripts:
    - jquery.min.js
    - bootstrapDaterangepickerMaster/moment.min.js
    - bootstrapDaterangepickerMaster/daterangepicker.js