generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           room
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          room
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Danh sách phòng game
        actions: {}
        object_actions: {}
        batch_actions: {}
      filter:
        display: [gameId]
      form:    ~
      edit:    ~
      new:     ~
